### ISSUE TITLE
Is 3.0.0-alpha1 RAC requirement necessary?

### ISSUE THREAD

**Issue by mbogh** [ashfurrow/Swift-RAC-Macros#4]
I have tested with RAC 2.4.7 and it seems to work just fine.

Would you consider lowering the RAC version requirement?

**Comment by ashfurrow** [comment]
Sure can – want to submit a PR to that effect? I can push to CocoaPods after that.

**Comment by mbogh** [comment]
Sure thing, will do it tomorrow :)

**Comment by ashfurrow** [comment]
Coooooool 0.2.2 is up on Trunk: https://raw.githubusercontent.com/CocoaPods/Specs/fcff81ca2ad5fb5a4c5812a09893f4535fe24804/Specs/Swift-RAC-Macros/0.2.2/Swift-RAC-Macros.podspec.json

![](http://media.giphy.com/media/V2xbsCrxcLQSQ/giphy.gif)
